package main

import (
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
	_ "modernc.org/sqlite"
)

type VOKDispatchSeed struct {
	Title string `json:"title"`
	Date  string `json:"date"`
	URL   string `json:"url"`
}

type ArticleRecord struct {
	URL         string
	Title       string
	PublishDate string
	RawBody     string
	BodyHash    string
	FetchedAt   time.Time
}

func initDB(dbPath string) (*sql.DB, error) {
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return nil, err
	}

	createTableQuery := `
	CREATE TABLE IF NOT EXISTS articles (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		url TEXT UNIQUE,
		title TEXT,
		publish_date TEXT,
		raw_body TEXT,
		body_hash TEXT,
		fetched_at DATETIME
	);
	CREATE INDEX IF NOT EXISTS idx_articles_hash ON articles(body_hash);
	CREATE INDEX IF NOT EXISTS idx_articles_date ON articles(publish_date);
	`
	_, err = db.Exec(createTableQuery)
	return db, err
}

func main() {
	// 1. Initialize SQLite Database
	db, err := initDB("archive.db")
	if err != nil {
		fmt.Printf("[-] Failed to initialize database: %v\n", err)
		return
	}
	defer db.Close()
	fmt.Println("[+] SQLite database initialized: archive.db")

	// 2. Load the seeds generated by vok_scraper
	seedData, err := os.ReadFile("vok_dispatches.json")
	if err != nil {
		fmt.Printf("[-] Failed to read vok_dispatches.json: %v\n", err)
		return
	}

	var seeds []VOKDispatchSeed
	if err := json.Unmarshal(seedData, &seeds); err != nil {
		fmt.Printf("[-] Failed to parse seed JSON: %v\n", err)
		return
	}

	// 3. Set up HTTP Client routed through Psiphon proxy
	proxyURL, _ := url.Parse("http://127.0.0.1:56827")
	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyURL(proxyURL),
		},
		Timeout: 35 * time.Second,
	}

	fmt.Printf("[*] Beginning ingestion for %d entries...\n\n", len(seeds))

	for i, seed := range seeds {
		// Skip non-article or video/audio-only links if we only want text articles first
		if seed.URL == "" || !strings.Contains(seed.URL, "detail_com/comde") && !strings.Contains(seed.URL, "revo_de/getDetail") {
			continue
		}

		// Check if URL is already archived
		var existingHash string
		err := db.QueryRow("SELECT body_hash FROM articles WHERE url = ?", seed.URL).Scan(&existingHash)
		if err == nil {
			fmt.Printf("[%d/%d] Skipping (Already Archived): %s\n", i+1, len(seeds), seed.Title)
			continue
		}

		fmt.Printf("[%d/%d] Ingesting: %s\n", i+1, len(seeds), seed.Title)

		bodyText, err := fetchArticleBody(client, seed.URL)
		if err != nil {
			fmt.Printf("    [-] Failed to retrieve body: %v\n", err)
			continue
		}

		if len(bodyText) == 0 {
			bodyText = seed.Title // fallback if article consists purely of headline
		}

		// Calculate SHA-256 hash of text content for integrity and change detection
		hash := sha256.Sum256([]byte(bodyText))
		bodyHash := hex.EncodeToString(hash[:])

		record := ArticleRecord{
			URL:         seed.URL,
			Title:       seed.Title,
			PublishDate: seed.Date,
			RawBody:     bodyText,
			BodyHash:    bodyHash,
			FetchedAt:   time.Now().UTC(),
		}

		err = saveArticle(db, record)
		if err != nil {
			fmt.Printf("    [-] DB Insert failed: %v\n", err)
		} else {
			fmt.Printf("    [+] Archived successfully (Hash: %s...)\n", bodyHash[:12])
		}

		// Polite delay to avoid stressing connection
		time.Sleep(1500 * time.Millisecond)
	}

	fmt.Println("\n[+] Full ingestion pass complete!")
}

func fetchArticleBody(client *http.Client, articleURL string) (string, error) {
	req, err := http.NewRequest("GET", articleURL, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) dprk-observer/0.1")

	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	doc, err := goquery.NewDocumentFromReader(resp.Body)
	if err != nil {
		return "", err
	}

	var paragraphs []string
	// VOK articles typically store dispatch body paragraphs within standard content containers
	doc.Find("p, div.content, .view_content").Each(func(i int, s *goquery.Selection) {
		text := strings.TrimSpace(s.Text())
		if len(text) > 30 && !strings.Contains(text, "Voice of Korea") {
			paragraphs = append(paragraphs, text)
		}
	})

	return strings.Join(paragraphs, "\n\n"), nil
}

func saveArticle(db *sql.DB, art ArticleRecord) error {
	query := `
	INSERT INTO articles (url, title, publish_date, raw_body, body_hash, fetched_at)
	VALUES (?, ?, ?, ?, ?, ?)
	ON CONFLICT(url) DO UPDATE SET
		raw_body = excluded.raw_body,
		body_hash = excluded.body_hash,
		fetched_at = excluded.fetched_at;
	`
	_, err := db.Exec(query, art.URL, art.Title, art.PublishDate, art.RawBody, art.BodyHash, art.FetchedAt)
	return err
}
